{% set name = "yggdrasil" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '
  skip: true  # [(win and vc<14) or py<35]
  entry_points:
    - yggdrasil = yggdrasil.command_line:main
    - ygginfo = yggdrasil.command_line:ygginfo
    - yggrun = yggdrasil.command_line:yggrun
    - cisrun = yggdrasil.command_line:yggrun
    - yggcompile = yggdrasil.command_line:yggcompile
    - yggcc = yggdrasil.command_line:yggcc
    - yggcctool = yggdrasil.command_line:cc_toolname
    - yggldtool = yggdrasil.command_line:ld_toolname
    - yggccflags = yggdrasil.command_line:cc_flags
    - yggldflags = yggdrasil.command_line:ld_flags
    - yggtest = yggdrasil.command_line:run_tsts
    - yggmetaschema = yggdrasil.command_line:regen_metaschema
    - yggschema = yggdrasil.command_line:regen_schema
    - yggbuildapi_c = yggdrasil.command_line:rebuild_c_api
    - yggconfig = yggdrasil.command_line:update_config
    - yggtime_comm = yggdrasil.command_line:yggtime_comm
    - yggtime_lang = yggdrasil.command_line:yggtime_lang
    - yggtime_os = yggdrasil.command_line:yggtime_os
    - yggtime_py = yggdrasil.command_line:yggtime_py
    - yggtime_paper = yggdrasil.command_line:yggtime_paper
    - yggvalidate = yggdrasil.command_line:validate_yaml
    - ygginstall = yggdrasil.command_line:ygginstall
    - yggdevup = yggdrasil.command_line:yggdevup
    - ygggha = yggdrasil.command_line:generate_gha_workflow

requirements:
  host:
    - czmq
    - pip
    - python
    - r-base
    - r-bit64
    - r-r6
    - r-reticulate
    - r-units
    - r-zeallot
    - sysv_ipc  # [unix]
    - zeromq
  run:
    - cmake  # [not win]
    - czmq
    - flaky
    - git
    - GitPython
    - jsonschema
    - matplotlib-base
    - numpy >=1.13.0
    - pandas
    - pyperf
    - pint  # [py2k]
    - psutil
    - pystache
    - python
    - python-rapidjson  # [not py2k]
    - pyyaml
    - pyzmq
    - r-base
    - r-bit64
    - r-r6
    - r-reticulate
    - r-units
    - r-zeallot
    - scipy
    - six
    - sysv_ipc  # [unix]
    - unyt  # [not py2k]
    - zeromq
    - {{ compiler('c') }}  # [win]
    - {{ compiler('cxx') }}  # [win]
    # - {{ compiler('fortran') }}  # [not win]
    # - fortran-compiler  # [not win]
    - m2w64-gcc-fortran  # [win]
    - m2w64-toolchain_win-64  # [win]

test:
  imports:
    - yggdrasil
  commands:
    - yggrun -h

about:
  home: https://github.com/cropsinsilico/yggdrasil
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A framework for connecting computational models from multiple languages.

  description: |
    The Crops in Silico (CiS) framework, yggdrasil, provides support for
    connecting scientific models written in different programming languages.
    To connect two models, modelers add communications interfaces to the model code
    and provide declarative specification files that identfy the
    models that should be run and the inputs and outputs those models
    expect. yggdrasil uses this information to launch the models
    on parallel processes and orchestrate asynchronous communication between them.
    Although designed for connecting crop models, yggdrasil can be used to
    connect scientific models from any domain.
  doc_url: https://cropsinsilico.github.io/yggdrasil
  dev_url: https://github.com/cropsinsilico/yggdrasil

extra:
  recipe-maintainers:
    - langmm
