name: Julia Testing
on: [push]
jobs:
  on_windows:
    runs-on: windows-latest
    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.2.3
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
    - name: Install PyCall
      run: julia -e "using Pkg; Pkg.add(\"PyCall\")"