name: Julia Testing
on: [push]
jobs:
  julia:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        install-method: [pip]
      fail-fast: false
      max-parallel: 20
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Python
      if: matrix.install-method == 'pip'
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    # - name: Install R
    #   if: matrix.install-method == 'pip'
    #   uses: r-lib/actions/setup-r@v2
    #   with:
    #     r-version: 4.2.3
    - name: Install Julia
      if: matrix.install-method == 'pip'
      uses: julia-actions/setup-julia@v1
    - name: Install PyCall
      if: matrix.install-method == 'pip'
      run: julia -e "using Pkg; Pkg.add(\"PyCall\")"